sonar.projectKey=zadanie6-zadanie6
sonar.organization=zadanie6
sonar.projectName=Zadanie6
sonar.host.url=https://sonarcloud.io
sonar.sources=projects/kotlin-project/src,projects/go-project,projects/js-projects/frontend/src,projects/js-projects/backend
sonar.exclusions=**/node_modules/**,**/build/**,**/vendor/**,**/.gradle/**,**/out/**
sonar.java.binaries=projects/kotlin-project/build/classes/java/main
sonar.language=java,js,go
